### PR TITLE
Add Logo

### PR DESCRIPTION
**Pull request by timthing**
Added the logo so it can be used in the readme.

### CODE REVIEW

**Comment by inooid** [comment]
Looks great! I'll probably add it to the read me in this PR as well. Great work! 👌

**Comment by inooid** [comment]
## Changes
- Removed the logo from the repo (https://github.com/inooid/Sketch-Plugin-Text-Extractor/pull/1/commits/37826386f6d03fa0e993f3597097b54727e698d6)
- Added logo to the read me (https://github.com/inooid/Sketch-Plugin-Text-Extractor/pull/1/commits/8a9149d795b548734d17801b8b0e133837198ca5)
- Added the roadmap of features that are coming up (https://github.com/inooid/Sketch-Plugin-Text-Extractor/pull/1/commits/2da69d9f2ac5bba7faae31dc11bdb24225e371b7)

Check the updated README here:
https://github.com/inooid/Sketch-Plugin-Text-Extractor/tree/logo

**Comment by timthing** [comment]
LGTM! 👍

**Review by inooid — APPROVED** [review]
LGTM 🎉 🚢

**Pull request merged**
